### ISSUE TITLE
Port can't be higher than 9999

### ISSUE THREAD

**Issue by Krush206** [Brko28/QtN2N_GUI#1]
I can't set a port which is higher than 9999. The app won't allow it

**Comment by Brko28** [comment]
I'm sorry about that. It will be fixed with a larger range of ports 0-65535.

**Comment by Krush206** [comment]
OK, I got it fixed but chat function doesn't seems to work. It connects successfully to the server but the chat log says 'Server not found!'. However, chat does work if it's a server hosted by QtN2N_GUI
